# Generated by Django 4.2.3 on 2024-10-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_confirmation_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_confirmation_sent",
            field=models.BooleanField(
                default=False, verbose_name="Zaplaceno -  potvrzení objednávky"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="confirmation_sent",
            field=models.BooleanField(
                default=False, verbose_name="Nezaplaceno - potvrzení objednávky"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipped_sent",
            field=models.BooleanField(
                default=False, verbose_name="Email - předáno k dopravci"
            ),
        ),
    ]
